# -*- coding: utf-8 -*-
"""political-violence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c4E1ghROwbv7uyX95D_ALMhY_a1bub8T
"""

import numpy as np
import pandas as pd
import geopandas as gpd
import plotly.express as px
import plotly.graph_objects as go
from geopy.distance import great_circle
import textwrap
import glob
import os

from google.colab import drive
drive.mount('/content/drive')

"""### Import Data"""

data_path = '/content/drive/MyDrive/independent-study/notebooks/ACLED/acled-data'
os.chdir(data_path)

df = pd.read_csv('acled-data.csv')
df.head()

"""#### Explore relevant information"""

df.info()

df['actor1'].unique()

"""### Choose relevant columns

Filter only for columns that are relevant in order to avoid clutter
"""

df = df[['event_date', 'year', 'event_type', 'sub_event_type', 'actor1', 'assoc_actor_1', 'actor2', 'assoc_actor_2', 'fatalities', 'admin1', 'civilian_targeting', 'country', 'latitude', 'longitude', 'notes']]
df.head()

df['notes_wrapped'] = df['notes'].apply(lambda txt: '<br>'.join(textwrap.wrap(txt, width=30)))

"""Filter out 2025 as the year is not complete and it could skew the visualizations that show change over time"""

df['year'] = df['year'].astype(int)
df = df[df['year'] != 2025]

"""### Classification
Classify actors into Palestinian and Israeli to provide for easier filtering in later steps

Based on all possible actors, choose keywords of Palestinian actors and Israeli Actors
"""

pal_keywords = [
    "Palestine",
    "Hamas",
    "PIJ",
    "Islamic Jihad",
    "Fatah",
    "AAMB",
    "PFLP",
    "DFLP",
    "Brigades",
    "Lions' Den",
    "Martyrs",
    "Resistance",
    "Katibat",
    "Mukhayyam",
    "Youth of Revenge",
    "Communal Militia (Palestine)",
    "Clan Militia (Palestine)"
]

israel_keywords = [
    "Israel",
    "IDF",
    "Israeli",
    "Settlers",
    "Shin Bet",
    "Golani",
    "Yamam",
    "Border Police",
    "Private Security Forces (Israel)",
    "Communal Militia (Israel)",
    "Clan Militia (Israel)"
]

"""Classify each actor and save into corresponding 'party' column"""

def classify_actor(actor):
    a = str(actor)

    # Palestinian
    if any(k in a for k in pal_keywords):
        return "Palestinian"

    # Israeli
    if any(k in a for k in israel_keywords):
        return "Israeli"

    # Other
    return "Other"

df['party1'] = df['actor1'].apply(classify_actor)
df['party2'] = df['actor2'].apply(classify_actor)
df['assoc_party1'] = df['assoc_actor_1'].apply(classify_actor)
df['assoc_party2'] = df['assoc_actor_2'].apply(classify_actor)

df.head()

"""### Filtering

#### Filter so each line has at least one Palestinian and one Israeli party
This way it can be ensured that all events being analyzed involve interaction between a Palestinian party and an Israeli party
"""

cols = ["party1", "party2", "assoc_party1", "assoc_party2"]

df = df[
    (df[cols].isin(["Israeli"]).any(axis=1)) &
    (df[cols].isin(["Palestinian"]).any(axis=1))
]
df.head()

"""#### Make df for political violence

Event types not specific enough to categorize
"""

df['event_type'].unique()

"""Observe sub-event types"""

df['sub_event_type'].unique()

"""Based on [ACLED Codebook](https://acleddata.com/methodology/acled-codebook), filter by sub-events that are categorized as political violence"""

allowed_sub_events = [
    "Mob violence",
    "Government regains territory",
    "Non-state actor overtakes territory",
    "Armed clash",
    "Excessive force against protesters",
    "Chemical weapon",
    "Air/drone strike",
    "Suicide bomb",
    "Shelling/artillery/missile attack",
    "Remote explosive/landmine/IED",
    "Grenade",
    "Sexual violence",
    "Attack",
    "Abduction/forced disappearance"
]

df_pv = df[df["sub_event_type"].isin(allowed_sub_events)]

df_pv.head()

df_pv.to_csv("pv_events.csv", index=False)

"""#### Create pv dfs for Palestine (and ones for the West Bank and Gaza) and Israel
This will be important when doing comparisons later

Palestine
"""

df_pv_pal = df_pv[df_pv['country'] == 'Palestine']

"""West Bank"""

df_pv_wb = df_pv[df_pv['admin1'] == 'West Bank']

"""Gaza"""

df_pv_gaza = df_pv[df_pv['admin1'] == 'Gaza Strip']

"""Israel"""

df_pv_israel = df_pv[df_pv['country'] == 'Israel']

"""### Create DataFrames for comparisons
* For each Palestinian location, concatenate their yearly DataFrame with Israel's
* Pivot by year and region with values as event count

Function to group each location's DataFrame by year
"""

def yearly_counts(df):
    return (
        df.groupby("year")
        .size()
        .reset_index(name="event_count")
    )

"""#### Palestine-Israel"""

yearly_pv_israel = yearly_counts(df_pv_israel)
yearly_pv_pal = yearly_counts(df_pv_pal)

# pivot into columns
pv_pivot = (
    pd.concat([
        yearly_pv_israel.assign(region="Israel"),
        yearly_pv_pal.assign(region="Palestine")
    ])
    .pivot(index="year", columns="region", values="event_count")
    .fillna(0)
)
pv_pivot

"""#### West Bank-Israel"""

yearly_pv_israel = yearly_counts(df_pv_israel)
yearly_pv_wb = yearly_counts(df_pv_wb)

# pivot into columns
pv_pivot_wb = (
    pd.concat([
        yearly_pv_israel.assign(region="Israel"),
        yearly_pv_wb.assign(region="West Bank")
    ])
    .pivot(index="year", columns="region", values="event_count")
    .fillna(0)
)
pv_pivot_wb

"""#### Gaza-Israel"""

yearly_pv_israel = yearly_counts(df_pv_israel)
yearly_pv_gaza = yearly_counts(df_pv_gaza)

# pivot into columns
pv_pivot_gaza = (
    pd.concat([
        yearly_pv_israel.assign(region="Israel"),
        yearly_pv_gaza.assign(region="Gaza Strip")
    ])
    .pivot(index="year", columns="region", values="event_count")
    .fillna(0)
)
pv_pivot_gaza

"""### Bar Chart"""

from plotly.subplots import make_subplots

fig = make_subplots(
    rows=2,
    cols=2,
    shared_yaxes=True,
    specs=[
        [{"colspan": 2}, None],   # Row 1: big subplot across both columns
        [{}, {}]                  # Row 2: two separate subplots
    ],
    vertical_spacing=0.07,
    row_heights=[5, 5],
    subplot_titles=(
        'Yearly Events: Palestine vs. Israel',
        'Yearly Events: West Bank vs. Israel',
        'Yearly Events: Gaza vs. Israel'
    )
)

# Pal-Is
fig.add_trace(
    go.Bar(
        name='Events in Palestine',
        x=pv_pivot.index,
        y=pv_pivot['Palestine']
    ),
    row=1,
    col=1
)
fig.add_trace(
    go.Bar(
        name='Events in Israel',
        x=pv_pivot.index,
        y=pv_pivot['Israel'],
        marker_color = '#ef553b',
        showlegend = False
    ),
    row=1,
    col=1
)

# WB-Is
fig.add_trace(
    go.Bar(
        name='Events in the West Bank',
        x=pv_pivot_wb.index,
        y=pv_pivot_wb['West Bank']
    ),
    row=2,
    col=1
)
fig.add_trace(
    go.Bar(
        name='Events in Israel',
        x=pv_pivot_wb.index,
        y=pv_pivot_wb['Israel'],
        marker_color = '#ef553b',
        showlegend = False
    ),
    row=2,
    col=1
)

# Gaza-Is
fig.add_trace(
    go.Bar(
        name='Events in the Gaza Strip',
        x=pv_pivot_gaza.index,
        y=pv_pivot_gaza['Gaza Strip']
    ),
    row=2,
    col=2
)
fig.add_trace(
    go.Bar(
        name='Events in Israel',
        x=pv_pivot_gaza.index,
        y=pv_pivot_gaza['Israel'],
        marker_color = '#ef553b'
    ),
    row=2,
    col=2
)

fig.update_layout(barmode='group', title_text='Yearly Political Violence Events Comparison (2016-2024)', width = 1000, height=1000, showlegend=True)
fig.update_xaxes(title_text='Year', row=1, col=1)
fig.update_xaxes(title_text='Year', row=2, col=1)
fig.update_xaxes(title_text='Year', row=2, col=2)
fig.update_yaxes(title_text='Number of Events', row=1, col=1)

fig.show()

fig.write_html('/content/drive/MyDrive/CS215/assignments/homework-06/hw-6-visualizations/pv_bar.html')

"""### Map"""

fig = go.Figure()

fig.add_trace(
    go.Densitymap(
      name = "Political Violence Events",
      lat = df_pv['latitude'],
      lon = df_pv['longitude'],
      radius = 6,
      text = df_pv['notes_wrapped'],
      hoverinfo = 'text'
    )
)

fig.add_trace(
    go.Scattermap(
        lat=df_pv['latitude'],   # use lat, not y
        lon=df_pv['longitude'],  # use lon, not x
        mode='markers',
        marker=dict(size=6, color='rgba(0,0,0,0)'),  # invisible
        text=df_pv['notes_wrapped'],
        hoverinfo='text',
        showlegend=False
    )
)

fig.update_layout(
    title=dict(
        text="Distribution of Political Violence Events (2016-2024)",
        x=0.5  # center the title
    ),
    autosize=False,
    width=900,
    height=900,
    map={
      'center': {'lat': 31.5, 'lon': 35},
      'zoom': 6.7
    }
)

fig.show()

df_pv.info()

fig.write_html('/content/drive/MyDrive/CS215/assignments/homework-06/hw-6-visualizations/pv-map.html')

df_2023 = df_pv[df_pv['year'] == 2023]
df_2023.head()

fig = go.Figure()

# fig.add_trace(
#     go.Densitymap(
#       name = "Political Violence Events",
#       lat = df_pv['latitude'],
#       lon = df_pv['longitude'],
#       radius = 6,
#       text = df_pv['notes_wrapped'],
#       hoverinfo = 'text'
#     )
# )

fig.add_trace(
    go.Scattermap(
        lat=df_pv['latitude'],   # use lat, not y
        lon=df_pv['longitude'],  # use lon, not x
        # mode='markers',
        # marker=dict(size=6, color='rgba(0,0,0,0)'),  # invisible
        text=df_pv['notes_wrapped'],
        hoverinfo='text',
        showlegend=False
    )
)

fig.update_layout(
    title=dict(
        text="Distribution of Political Violence Events (2016-2024)",
        x=0.5  # center the title
    ),
    autosize=False,
    width=900,
    height=900,
    map={
      'center': {'lat': 31.5, 'lon': 35},
      'zoom': 6.7
    }
)

fig.show()

fig.write_html('/content/drive/MyDrive/CS215/assignments/homework-06/hw-6-visualizations/pv-alt-map.html')

"""### Pie chart"""

fig = make_subplots(
    rows=1,
    cols=2,
    subplot_titles=(
        'West Bank',
        'Gaza Strip'
    ),
    specs=[[{'type':'domain'}, {'type':'domain'}]]
)

fig.add_trace(
    go.Pie(
        labels = df_pv_wb['sub_event_type'].value_counts().index,
        values = df_pv_wb['sub_event_type'].value_counts().values
    ),
    row = 1,
    col = 1
)

fig.add_trace(
    go.Pie(
        labels = df_pv_gaza['sub_event_type'].value_counts().index,
        values = df_pv_gaza['sub_event_type'].value_counts().values
    ),
    row = 1,
    col = 2
)

fig.update_layout(
    title_text="Distribution of Political Violence Event Types in the West Bank and the Gaza Strip",
    height=800, width=1000,  # Reduce width to make them closer
    margin=dict(l=50, r=50, t=100, b=50),  # Reduce side margins
)

fig.show()

fig.write_html('/content/drive/MyDrive/CS215/assignments/homework-06/hw-6-visualizations/pv-pie.html')